config/routes.rb
Rails.application.routes.draw do
  resources :weekly_plans
  resources :ingredients
  resources :recipes
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  post 'recipe/:id/ingredient', to: 'recipes#new_ingredient', as: 'new_recipe_ingredient'
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/recipe.rb
class Recipe < ApplicationRecord
    has_many :recipe_ingredients
    has_one_attached :photo
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: %i[ show edit update destroy new_ingredient]

  # GET /recipes or /recipes.json
  def index
    @recipes = Recipe.all
  end

  # GET /recipes/1 or /recipes/1.json
  def show
    
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
    @ingredients = Ingredient.all
  end

  # GET /recipes/1/edit
  def edit
    @ingredients = Ingredient.all
  end

  # POST /recipes or /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to recipe_url(@recipe), notice: "Recipe was successfully created." }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1 or /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to recipe_url(@recipe), notice: "Recipe was successfully updated." }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1 or /recipes/1.json
  def destroy
    @recipe.destroy

    respond_to do |format|
      format.html { redirect_to recipes_url, notice: "Recipe was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def new_ingredient
    recipe_ingredient = @recipe.recipe_ingredients.create
    ingredient = Ingredient.find(params[:ingredient])
    recipe_ingredient.ingredient = ingredient
    recipe_ingredient.quantity = params[:recipe_ingredient][:quantity]

    respond_to do |format|
      if recipe_ingredient.save
        format.html { redirect_to edit_recipe_path(@recipe), notice: "Ingredient added" }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: recipe_ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def recipe_params
      params.require(:recipe).permit(:title, :method, :ingredients, :serves, :photo)
    end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<%= form_with(model: recipe) do |form| %>
  <% if recipe.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
        <% recipe.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="field-row">
    <%= form.label :photo, class: 'form-label' %>
    <%= form.file_field :photo, class: 'form-control' %>
  </div>

  <div class="field-row">
    <%= form.label :serves, class: 'form-label' %>
    <%= form.number_field :serves, class: 'form-control' %>
  </div>

  <div>
    <%= form.label :method, style: "display: block" %>
    <%= form.text_area :method, class: 'tinymce' %>
  </div>

  <div>
    <%= form.submit nil, class: 'btn btn-primary mt-4' %>
  </div>
<% end %>

<script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script>
<script>
$(function(){
   tinymce.init({
     selector: '.tinymce',
     height: 500,
     menubar: false,
     plugins: [
       'advlist autolink lists link image charmap print preview anchor',
       'searchreplace visualblocks code fullscreen',
       'insertdatetime media table paste code help wordcount'
     ],
       toolbar: 'undo redo | formatselect | ' +
       'bold italic backcolor | alignleft aligncenter ' +
       'alignright alignjustify | bullist numlist outdent indent | ' +
       ' removeformat | help'
   });
});
</script>

app/views/recipes/_recipe.html.erb
<div id="<%= dom_id recipe %>">
  <div class="row">
    <div class="col-md-12">
      <h1> <%= recipe.title %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12">
      <div class="recipe-cover">
        <%= image_tag recipe.photo %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-4">
      <div class="mb-4">
        <strong>Serves: <%= recipe.serves %></strong>
      </div>
      <strong>Ingredients</strong>
      <% recipe.recipe_ingredients.each do |ingredient| %>
        <p><%= "#{ingredient.ingredient.name} | #{number_with_precision(ingredient.quantity, precision: 2,  strip_insignificant_zeros: true)} #{ingredient.ingredient.measurement}" %></p>
      <% end %>
    </div>
    <div class="col-md-8">
      <h2>Method</h2>
      <%= raw(recipe.method) %>
    </div>
  </div>
</div>

app/views/recipes/edit.html.erb
<h1>Editing recipe</h1>

<%= render "form", recipe: @recipe %>

<br>


<h2>Ingredients</h2>
<% @recipe.recipe_ingredients.each do |ingredient| %>
  <p><%= ingredient.ingredient.name + " | " + ingredient.quantity.to_s + ingredient.ingredient.measurement %>
<% end %>
<h2>Add ingredients</h2>
<%= form_for :recipe_ingredient, url: new_recipe_ingredient_path(@recipe.id) do |form| %>
  <div>
    <%= select_tag "ingredient", options_from_collection_for_select(@ingredients, "id", "name") %>
  </div>
  <div>
    <%= form.label :quantity, style: "display: block" %>
    <%= form.number_field :quantity %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

<div>
  <%= button_to "Destroy this recipe", @recipe, method: :delete %>
</div>


<style>
.custom-combobox {
    position: relative;
    display: inline-block;
  }
  .custom-combobox-toggle {
    position: absolute;
    top: 0;
    bottom: 0;
    margin-left: -1px;
    padding: 0;
  }
  .custom-combobox-input {
    margin: 0;
    padding: 5px 10px;
  }
  .ui-menu-item{
    list-style: none;
    border: 1px solid #000;
    z-index: 9999;
    background: white;
  }
  .ui-menu-item a{
    color: black;
    text-decoration: none;
    width: 100%;
  }
</style>
<script>
$( function() {
    $.widget( "custom.combobox", {
      _create: function() {
        this.wrapper = $( "<span>" )
          .addClass( "custom-combobox" )
          .insertAfter( this.element );
 
        this.element.hide();
        this._createAutocomplete();
        this._createShowAllButton();
      },
 
      _createAutocomplete: function() {
        var selected = this.element.children( ":selected" ),
          value = selected.val() ? selected.text() : "";
 
        this.input = $( "<input>" )
          .appendTo( this.wrapper )
          .val( value )
          .attr( "title", "" )
          .addClass( " form-control custom-combobox-input ui-widget ui-widget-content ui-state-default ui-corner-left" )
          .autocomplete({
            delay: 0,
            minLength: 0,
            source: this._source.bind( this )
          })
          .tooltip({
            classes: {
              "ui-tooltip": "ui-state-highlight"
            }
          });
 
        this._on( this.input, {
          autocompleteselect: function( event, ui ) {
            ui.item.option.selected = true;
            this._trigger( "select", event, {
              item: ui.item.option
            });
          },
 
          autocompletechange: "_removeIfInvalid"
        });
      },
 
      _createShowAllButton: function() {
        var input = this.input,
          wasOpen = false;
 
        $( "<a>" )
          .attr( "tabIndex", -1 )
          .attr( "title", "Show All Items" )
          .tooltip()
          .appendTo( this.wrapper )
          .button({
            icons: {
              primary: "ui-icon-triangle-1-s"
            },
            text: false
          })
          .removeClass( "ui-corner-all" )
          .addClass( "custom-combobox-toggle ui-corner-right" )
          .on( "mousedown", function() {
            wasOpen = input.autocomplete( "widget" ).is( ":visible" );
          })
          .on( "click", function() {
            input.trigger( "focus" );
 
            // Close if already visible
            if ( wasOpen ) {
              return;
            }
 
            // Pass empty string as value to search for, displaying all results
            input.autocomplete( "search", "" );
          });
      },
 
      _source: function( request, response ) {
        var matcher = new RegExp( $.ui.autocomplete.escapeRegex(request.term), "i" );
        response( this.element.children( "option" ).map(function() {
          var text = $( this ).text();
          if ( this.value && ( !request.term || matcher.test(text) ) )
            return {
              label: text,
              value: text,
              option: this
            };
        }) );
      },
 
      _removeIfInvalid: function( event, ui ) {
 
        // Selected an item, nothing to do
        if ( ui.item ) {
          return;
        }
 
        // Search for a match (case-insensitive)
        var value = this.input.val(),
          valueLowerCase = value.toLowerCase(),
          valid = false;
        this.element.children( "option" ).each(function() {
          if ( $( this ).text().toLowerCase() === valueLowerCase ) {
            this.selected = valid = true;
            return false;
          }
        });
 
        // Found a match, nothing to do
        if ( valid ) {
          return;
        }
 
        // Remove invalid value
        this.input
          .val( "" )
          .attr( "title", value + " didn't match any item" )
          .tooltip( "open" );
        this.element.val( "" );
        this._delay(function() {
          this.input.tooltip( "close" ).attr( "title", "" );
        }, 2500 );
        this.input.autocomplete( "instance" ).term = "";
      },
 
      _destroy: function() {
        this.wrapper.remove();
        this.element.show();
      }
    });
 
    $( "#ingredient" ).combobox();
    $( "#toggle" ).on( "click", function() {
      $( "#ingredient" ).toggle();
    });
  } );
</script>

<div>
  <%= link_to "Show this recipe", @recipe %> |
  <%= link_to "Back to recipes", recipes_path %>
</div>

app/views/recipes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Recipes</h1>

<%= link_to "New recipe", new_recipe_path, class: 'btn btn-primary mb-4' %>
<div id="recipes" class="row">
  <% @recipes.each do |recipe| %>
  <div class="col-md-4 card">
    <div class="card-body">
      <p>
        <%= recipe.title %>
      </p>
      <p>
        <%= link_to "View", recipe %>
        <%= link_to "Edit", edit_recipe_path(recipe.id)%>
      </p>
    </div>
  </div>
  <% end %>
</div>

app/views/recipes/new.html.erb
<h1>New recipe</h1>

<%= render "form", recipe: @recipe %>

<br>

<div>
  <%= link_to "Back to recipes", recipes_path %>
</div>

app/views/recipes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @recipe %>