config/routes.rb
Rails.application.routes.draw do
  resources :weekly_plans
  resources :ingredients
  resources :recipes
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  post 'recipe/:id/ingredient', to: 'recipes#new_ingredient', as: 'new_recipe_ingredient'
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
    has_many :recipe_ingredients
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :set_ingredient, only: %i[ show edit update destroy ]

  # GET /ingredients or /ingredients.json
  def index
    @ingredients = Ingredient.all.order(name: :asc)
  end

  # GET /ingredients/1 or /ingredients/1.json
  def show
  end

  # GET /ingredients/new
  def new
    @ingredient = Ingredient.new
  end

  # GET /ingredients/1/edit
  def edit
  end

  # POST /ingredients or /ingredients.json
  def create
    @ingredient = Ingredient.new(ingredient_params)

    respond_to do |format|
      if @ingredient.save
        format.html { redirect_to ingredient_url(@ingredient), notice: "Ingredient was successfully created." }
        format.json { render :show, status: :created, location: @ingredient }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ingredients/1 or /ingredients/1.json
  def update
    respond_to do |format|
      if @ingredient.update(ingredient_params)
        format.html { redirect_to ingredient_url(@ingredient), notice: "Ingredient was successfully updated." }
        format.json { render :show, status: :ok, location: @ingredient }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ingredients/1 or /ingredients/1.json
  def destroy
    @ingredient.destroy

    respond_to do |format|
      format.html { redirect_to ingredients_url, notice: "Ingredient was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ingredient
      @ingredient = Ingredient.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ingredient_params
      params.require(:ingredient).permit(:name, :measurement)
    end
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/ingredients/_form.html.erb
<%= form_with(model: ingredient) do |form| %>
  <% if ingredient.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(ingredient.errors.count, "error") %> prohibited this ingredient from being saved:</h2>

      <ul>
        <% ingredient.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :measurement, style: "display: block" %>
    <%= form.text_field :measurement %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/ingredients/_ingredient.html.erb
<div id="<%= dom_id ingredient %>">
  <p>
    <strong>Name:</strong>
    <%= ingredient.name %>
  </p>

  <p>
    <strong>Measurement:</strong>
    <%= ingredient.measurement %>
  </p>

</div>

app/views/ingredients/edit.html.erb
<h1>Editing ingredient</h1>

<%= render "form", ingredient: @ingredient %>

<br>

<div>
  <%= link_to "Show this ingredient", @ingredient %> |
  <%= link_to "Back to ingredients", ingredients_path %>
</div>

app/views/ingredients/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Ingredients</h1>

<%= link_to "New ingredient", new_ingredient_path, class: 'btn btn-primary mb-4' %>
<div id="ingredients" class="row">
  <% @ingredients.each do |ingredient| %>
    <div class="col-md-4 card">
    <div class="card-body">
      <p>
        <%= ingredient.name %>
      </p>
      <div class="row">
        <div class="col-md-4">
          <%= link_to "View", ingredient, class: 'btn btn-outline-primary btn-justify' %>
        </div>
        <div class="col-md-4">
          <%= link_to "Edit", edit_ingredient_path(ingredient.id), class: 'btn btn-outline-secondary' %>
        </div>
        <div class="col-md-4">
          <%= button_to "Destroy", ingredient, method: :delete, class: 'btn btn-outline-danger' %>
        </div>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/ingredients/new.html.erb
<h1>New ingredient</h1>

<%= render "form", ingredient: @ingredient %>

<br>

<div>
  <%= link_to "Back to ingredients", ingredients_path %>
</div>

app/views/ingredients/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @ingredient %>

<div>
  <%= link_to "Edit this ingredient", edit_ingredient_path(@ingredient) %> |
  <%= link_to "Back to ingredients", ingredients_path %>

  <%= button_to "Destroy this ingredient", @ingredient, method: :delete %>
</div>