config/routes.rb
Rails.application.routes.draw do
  resources :weekly_plans
  resources :ingredients
  resources :recipes
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  post 'recipe/:id/ingredient', to: 'recipes#new_ingredient', as: 'new_recipe_ingredient'
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/weekly_plan.rb
class WeeklyPlan < ApplicationRecord
    has_many :meals, dependent: :delete_all
end

app/controllers/weekly_plans_controller.rb
class WeeklyPlansController < ApplicationController
  before_action :set_weekly_plan, only: %i[show edit update destroy]

  # GET /weekly_plans or /weekly_plans.json
  def index
    @weekly_plans = WeeklyPlan.all
  end

  # GET /weekly_plans/1 or /weekly_plans/1.json
  def show
    @ingredients = []
    @combined = []
    @weekly_plan.meals.each do | meal |
      meal.recipe.recipe_ingredients.each do | ingredient |
        ingredient.quantity = ingredient.quantity / (meal.recipe.serves.to_f / meal.people.to_f)
        @ingredients.push(ingredient)
      end
    end

    @ingredients.each do |ingredient|
      if @combined.select {|x| x.ingredient_id == ingredient.ingredient_id}.any?
        @combined.select {|x| x.ingredient_id == ingredient.ingredient_id}.first.quantity += ingredient.quantity
      else
        @combined.push(ingredient)
      end
    end
  end

  # GET /weekly_plans/new
  def new
    @weekly_plan = WeeklyPlan.new
    @recipes = Recipe.all
    @weekdays = %w[Monday Tuesday Wednesday Thursday Friday Saturday Sunday]
  end

  # GET /weekly_plans/1/edit
  def edit
    @recipes = Recipe.all
    @weekdays = %w[Monday Tuesday Wednesday Thursday Friday Saturday Sunday]
  end

  # POST /weekly_plans or /weekly_plans.json
  def create
    @weekly_plan = WeeklyPlan.new(weekly_plan_params)
    respond_to do |format|
      if @weekly_plan.save
        (0..6).each do |day|
          (0..2).each do |meal_type|
            meal = @weekly_plan.meals.create
            meal.recipe = Recipe.find(params["#{meal_type}_recipe_#{day}"])
            meal.people = params[:weekly_plan]["#{meal_type}_people_#{day}"]
            meal.date = day
            meal.meal_type = meal_type
            meal.save
          end
        end

        format.html { redirect_to weekly_plan_url(@weekly_plan), notice: 'Weekly plan was successfully created.' }
        format.json { render :show, status: :created, location: @weekly_plan }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @weekly_plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /weekly_plans/1 or /weekly_plans/1.json
  def update
    respond_to do |format|
      if @weekly_plan.update(weekly_plan_params)
        @weekly_plan.meals.delete_all
        (0..6).each do |day|
          (0..2).each do |meal_type|
            meal = @weekly_plan.meals.create
            meal.recipe = Recipe.find(params["#{meal_type}_recipe_#{day}"])
            meal.people = params[:weekly_plan]["#{meal_type}_people_#{day}"]
            meal.date = day
            meal.meal_type = meal_type
            meal.save
          end
        end

        format.html { redirect_to weekly_plan_url(@weekly_plan), notice: 'Weekly plan was successfully updated.' }
        format.json { render :show, status: :ok, location: @weekly_plan }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @weekly_plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /weekly_plans/1 or /weekly_plans/1.json
  def destroy
    @weekly_plan.destroy

    respond_to do |format|
      format.html { redirect_to weekly_plans_url, notice: 'Weekly plan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_weekly_plan
    @weekly_plan = WeeklyPlan.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def weekly_plan_params
    params.require(:weekly_plan).permit(:start_date)
  end
end

app/helpers/weekly_plans_helper.rb
module WeeklyPlansHelper
end

app/views/weekly_plans/_form.html.erb
<%= form_with(model: weekly_plan) do |form| %>
  <% if weekly_plan.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(weekly_plan.errors.count, "error") %> prohibited this weekly_plan from being saved:</h2>

      <ul>
        <% weekly_plan.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :start_date, style: "display: block" %>
    <%= form.date_field :start_date, class: 'form-control' %>
  </div>

  <% (0..6).each do |i| %>
  <div class="row mt-4 mb-4">
    <div class="col-md-12">
      <h4><%= @weekdays[i]%></h4>
    </div>
    <div class="col-md-3">
      <%= form.label :meal, 'Breakfast' %>
      <%= select_tag "0_recipe_#{i}", options_from_collection_for_select(@recipes, "id", "title"), class: 'form-control' %>
    </div>
    <div class="col-md-1">
      <%= form.label :people %>
      <%= form.number_field "0_people_#{i}", class: 'form-control'  %>
    </div>
    <div class="col-md-3">
      <%= form.label :meal, 'Lunch'%>
      <%= select_tag "1_recipe_#{i}", options_from_collection_for_select(@recipes, "id", "title"), class: 'form-control'  %>
    </div>
    <div class="col-md-1">
      <%= form.label :people %>
      <%= form.number_field "1_people#{i}", class: 'form-control'  %>
    </div>
    <div class="col-md-3">
      <%= form.label :meal, 'Dinner'%>
      <%= select_tag "2_recipe_#{i}", options_from_collection_for_select(@recipes, "id", "title"), class: 'form-control'  %>
    </div>
    <div class="col-md-1">
      <%= form.label :people %>
      <%= form.number_field "2_people_#{i}", class: 'form-control'  %>
    </div>
  <div>
  <% end %>

    <%= form.submit nil, class: 'btn btn-primary mt-4' %>
  </div>
<% end %>

app/views/weekly_plans/_weekly_plan.html.erb
<% 
  @weekdays = %w[Monday Tuesday Wednesday Thursday Friday Saturday Sunday]
  @meal_types = %w[Breakfast Lunch Dinner]
%>

<div id="<%= dom_id weekly_plan %>">
  <h1>Plan for <%= weekly_plan.start_date.strftime("%d %B") %></h1>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Day</th>
        <th>Breakfast</th>
        <th>Lunch</th>
        <th>Dinner</th>
      </tr>
    </thead>
    <tbody>

      <% (0..6).each do | i | %>
        <tr>
          <td><%= @weekdays[i] %></td>
          <% weekly_plan.meals.select { |x| x.date == i}.each do | meal | %>
            <td><%= link_to meal.recipe.title, recipe_path(meal.recipe.id) %> for <%= meal.people %> </td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>

  <h2>Total Required Ingredients</h2>
  <% @combined.each do |ingredient|%>
    <p><%= "#{ingredient.ingredient.name} | #{number_with_precision(ingredient.quantity, precision: 2,  strip_insignificant_zeros: true)} #{ingredient.ingredient.measurement}" %></p>
  <% end %>
</div>

app/views/weekly_plans/edit.html.erb
<h1>Editing weekly plan</h1>

<%= render "form", weekly_plan: @weekly_plan %>

<br>

<div>
  <%= link_to "Show this weekly plan", @weekly_plan %> |
  <%= link_to "Back to weekly plans", weekly_plans_path %>
</div>

app/views/weekly_plans/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Weekly plans</h1>

<div id="weekly_plans">
  <% @weekly_plans.each do |weekly_plan| %>
    <p>
      Plan for <%= weekly_plan.start_date %>
    </p>
    <p>
      <%= link_to "Show Plan", weekly_plan %>
      <%= link_to "Edit Plan", edit_weekly_plan_path(weekly_plan) %>
    </p>
  <% end %>
</div>

<%= link_to "New weekly plan", new_weekly_plan_path %>

app/views/weekly_plans/new.html.erb
<h1>New weekly plan</h1>

<%= render "form", weekly_plan: @weekly_plan %>

<br>

<div>
  <%= link_to "Back to weekly plans", weekly_plans_path, class: 'btn btn-outline-secondary' %>
</div>

app/views/weekly_plans/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @weekly_plan %>

<div class="btn-group">
  <%= link_to "Edit this weekly plan", edit_weekly_plan_path(@weekly_plan), class: 'btn btn-outline-secondary' %>
  <%= link_to "Back to weekly plans", weekly_plans_path, class: 'btn btn-outline-secondary' %>
  <%= button_to "Destroy this weekly plan", @weekly_plan, method: :delete, class: 'btn btn-outline-danger' %>
</div>